### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by Saloed** [Yuichir0/Chess#1]
1. Настроек локальной среды разработки (`.idea`) в репозитории быть не должно
2. Нет тестов на логику игры и на интерфйес
3. А почему не просто `moveFromPlayer`? [link](https://github.com/Yuichir0/Chess/blob/2f4475b58dde0a75d355560832fb418d8cc65f11/app/src/main/java/com/example/android_chess/MainActivity.kt#L38)
4. А зачем это здесь? [link](https://github.com/Yuichir0/Chess/blob/2f4475b58dde0a75d355560832fb418d8cc65f11/app/src/main/java/com/example/android_chess/ChessFront.kt#L84)
5. Обычно игнорировать предупреждения это не очень хорошо. Тут это точно обосновано? [link](https://github.com/Yuichir0/Chess/blob/2f4475b58dde0a75d355560832fb418d8cc65f11/app/src/main/java/com/example/android_chess/ChessFront.kt#L52)
6. Держать drawable в ChessPiece это не очень хорошо, поскольку из-за этого штука, связанная с интерфейсом, просачивается в `back`. Лучше как-то хитрее организовать [`bitmaps`](https://github.com/Yuichir0/Chess/blob/2f4475b58dde0a75d355560832fb418d8cc65f11/app/src/main/java/com/example/android_chess/ChessFront.kt#L101). Например, можно использовать в качестве ключа пару из `ChessPlayer` и `ChessPieceType`
7. Кажется, довольно часто хочется искать фигуры по их координатам на доске. Может просто множество это не лучший способ представления? [link](https://github.com/Yuichir0/Chess/blob/2f4475b58dde0a75d355560832fb418d8cc65f11/app/src/main/java/com/example/android_chess/ChessBack.kt#L6)
8. Есть очень большие повторяющиеся куски кода. Например, [вот](https://github.com/Yuichir0/Chess/blob/master/app/src/main/java/com/example/android_chess/ChessBack.kt#L307-L375) и [вот](https://github.com/Yuichir0/Chess/blob/master/app/src/main/java/com/example/android_chess/ChessBack.kt#L465-L534) отличаются только заменой `possibleMoves` на `legalMoves`.
9. В именах пакетов принято использовать `camelCase`.

**Comment by Yuichir0** [comment]
1 Если правильно понял - исправил
2 Добавил
3 Исправил
5  Исправил
6 Если я правильно помню, R.drawable. хранится в виде целочисленного идентификатора по умолчанию. Разве использование по другому образованного ключа будет целесообразно?
8 Исправил
9 Вроде бы исправил
